<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HSWEBDEV323" name="Test(failed)(failed)(failed)" tests="1" failures="1" timestamp="10 Jan 2016 02:22:11 GMT" time="94.674" errors="0">
  <testcase name="verifyLoginLogoutTwo on [Test: &quot;null&quot; verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:] " time="90.775" classname="Tests.LoginTestTwo">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at Tests.LoginTestTwo.verifyLoginLogoutTwo(LoginTestTwo.java:28)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- verifyLoginLogoutTwo on [Test: "null" verbose:1[parameters:][metagroups:] [included: ][excluded: ]  classes: packages:]  -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
